### PR TITLE
Getting Started to RTD

### PR DESCRIPTION
**Pull request by amolenaar**
On RTD we have a more up-to-date version of the Getting Started and First Model docs.

However, those docs are translated, and on RTD they're not. Should we keep the original tutorials on gaphor.org or direct people to RTD early on?

@danyeaw Any thoughts?

### CODE REVIEW

**Comment by danyeaw** [comment]
Hi @amolenaar, this is a tough one because I agree that these Getting Started Docs need to be updated and improved. My mental model was that gaphor.org was for users of the tool and gaphor.readthedocs.io was for developers. However, I also agree that keeping docs up to date in two places is a challenge.

Maybe I should shift my mental model and gaphor.org is all the "sales" info, and gaphor.readthedocs.io provides all the other documentation.

**Comment by amolenaar** [comment]
The RTD docs already contains the feature docs (css, jupyter, etc.), so the whole user/dev division is already a bit skewed.

I like the idea that the whole usage reference is on RTD and is kept in sync with the latest version of Gaphor. We can also publish docs for older versions if we like.

The only thing is that the current getting started docs have been translated. The RTD docs do not have transation support atm.

**Review by danyeaw — APPROVED** [review]

**Comment by danyeaw** [comment]
Good idea, I opened a Gaphor issue for us to translate our RTD docs.

**Comment by amolenaar** [comment]
Maybe we should also move "How to report a bug" to rtd? What do you think, @danyeaw?

**Comment by danyeaw** [comment]
Sounds good to me!

**Comment by danyeaw** [comment]
@amolenaar One additional thing we could do is use a custom domain with RTD. So https://docs.gaphor.org would have our RTD docs.

**Pull request merged**
