### PR TITLE
Add Russian translation

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Gaphor/gaphor.github.io](https://hosted.weblate.org/projects/gaphor/gaphor-github-io/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by danyeaw** [comment]
Thanks @BrainKicker! We'll also need to add Russian to the top navigation so that it can be selected. Would you be interested in submitting a PR for this as well?

**Comment by BrainKicker** [comment]
At the moment I haven't started working on the website translation.
About the navigation: do you want me to modify the .html files? There isn't a Russian version of the website yet. Isn't it created automatically so I just need to translate strings on Weblate?

**Comment by danyeaw** [comment]
Hi @BrainKicker, I rebuilt the translations and added Russian to the `po/po4a.conf` and `_data/languages.yml` files. Russian is now selectable in the top navigation.

**Comment by BrainKicker** [comment]
Hi @danyeaw! I don't think it's time to add Russian to the top navigation, because it's 0% complete.

**Comment by danyeaw** [comment]
Ok, I can remove it for now. To be honest, I'm fine with it up there as long as we can get some of the strings translated short term

**Comment by BrainKicker** [comment]
Good. This is your site after all. Then I will do the translation, but I can't promise the timing.

**Pull request merged**
